# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "aws_upload_datasource_name" {
  value = "${module.env-dashboards.aws_upload_datasource_name}"
}

output "dashboards" {
  value = "${module.env-dashboards.dashboards}"
}

output "datasources" {
  value = "${module.env-dashboards.datasources}"
}

output "gcp_analysis_datasource_name" {
  value = "${module.env-dashboards.gcp_analysis_datasource_name}"
}

