# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "datasources" {
  value = "${module.env-dashboards.datasources}"
}

output "dcp_dashboard" {
  value = "${module.env-dashboards.dcp_dashboard}"
}

output "dss_dashboard" {
  value = "${module.env-dashboards.dss_dashboard}"
}
