# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "dcp_dashboard_json" {
  value = "${module.dashboards.dcp_dashboard_json}"
}

output "dss_dashboard_json" {
  value = "${module.dashboards.dss_dashboard_json}"
}

output "logs_dashboard_json" {
  value = "${module.dashboards.logs_dashboard_json}"
}
