# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "singleton-alerts" {
  source                          = "../../../modules/singleton-alerts"
  aws_profile                     =  local.aws_profile
  metadata_schema_health_check_id =  local.metadata_schema_health_check_id
}
