#!/usr/bin/env python
import argparse
import json
import requests
import sys

cli = argparse.ArgumentParser(description=__doc__)
cli.add_argument('--grafana-user', dest="user", type=str, required=True)
cli.add_argument('--grafana-password', dest="password", type=str, required=True)
cli.add_argument('--env', dest="env", choices=["dev", "integration", "staging", "prod"], required=True)
cli.add_argument('dashboard_json', nargs='?', type=str, default=''.join(sys.stdin))
options = cli.parse_args(sys.argv[1:])

body = '{"dashboard":' + options.dashboard_json + ', "overwrite": true}'

domain = {
    "dev": ".dev",
    "integration": ".dev",
    "staging": ".dev",
    "prod": "",
}[options.env]

url = "https://{}:{}@metrics{}.data.humancellatlas.org/api/dashboards/db".format(
    options.user,
    options.password,
    domain
)

response = requests.post(
    url,
    data=body,
    headers={
        'Content-Type': 'application/json'
    }
)

print("{} {} {}".format(response.status_code, url, response.content))
