# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "account_dashboard" {
  value = "${module.account-dashboards.account_dashboard}"
}

output "aws_cloudwatch_data_source_name" {
  value = "${module.account-dashboards.aws_cloudwatch_data_source_name}"
}

output "aws_logs_data_source_name" {
  value = "${module.account-dashboards.aws_logs_data_source_name}"
}

output "datasources" {
  value = "${module.account-dashboards.datasources}"
}

output "gcp_log_project_datasource_name" {
  value = "${module.account-dashboards.gcp_log_project_datasource_name}"
}

output "logs_dashboard" {
  value = "${module.account-dashboards.logs_dashboard}"
}
