# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "singleton-health-checks" {
  source = "../../../modules/singleton-health-checks"
  env    = "${local.env}"
  region = "${local.region}"
}
