# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "metadata_schema_health_check_id" {
  value =  module.singleton-health-checks.metadata_schema_health_check_id
}
