# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "analysis_health_check_id" {
  value = "${module.env-health-checks.analysis_health_check_id}"
}

output "azul_indexer_health_check_id" {
  value = "${module.env-health-checks.azul_indexer_health_check_id}"
}

output "azul_webservice_health_check_id" {
  value = "${module.env-health-checks.azul_webservice_health_check_id}"
}

output "data_browser_health_check_id" {
  value = "${module.env-health-checks.data_browser_health_check_id}"
}

output "dcp_health_check_id" {
  value = "${module.env-health-checks.dcp_health_check_id}"
}

output "dss_health_check_id" {
  value = "${module.env-health-checks.dss_health_check_id}"
}

output "ingest_health_check_id" {
  value = "${module.env-health-checks.ingest_health_check_id}"
}

output "matrix_health_check_id" {
  value = "${module.env-health-checks.matrix_health_check_id}"
}

output "upload_health_check_id" {
  value = "${module.env-health-checks.upload_health_check_id}"
}
