# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "analysis_health_check_id" {
  value = "${module.health-checks.analysis_health_check_id}"
}

output "dcp_health_check_id" {
  value = "${module.health-checks.dcp_health_check_id}"
}

output "dss_health_check_id" {
  value = "${module.health-checks.dss_health_check_id}"
}

output "ingest_health_check_id" {
  value = "${module.health-checks.ingest_health_check_id}"
}

output "logs_health_check_id" {
  value = "${module.health-checks.logs_health_check_id}"
}

output "upload_health_check_id" {
  value = "${module.health-checks.upload_health_check_id}"
}
