#!/bin/sh

OPTION="$1"

eval "$(jq -r '@sh "CALLER_REFERENCE_PREFIX=\(.caller_reference_prefix) AWS_PROFILE=\(.aws_profile)"')"

case "$OPTION" in
  --children)
    IDS=$(aws route53 list-health-checks --profile "$AWS_PROFILE" | \
      jq -r ".HealthChecks[] | \
      select(.CallerReference) | \
      select(.CallerReference | \
      startswith(\"$CALLER_REFERENCE_PREFIX\")) | \
      .HealthCheckConfig | \
      .ChildHealthChecks[]")
    c=0
    result='. '
    for id in $IDS; do
      result+="| .child_id$c = \"$id\""
      c=$(($c + 1))
    done
    jq -n "$result"
    ;;
  *)
    aws route53 list-health-checks --profile "$AWS_PROFILE" | \
      jq ".HealthChecks[] | \
      select(.CallerReference) | \
      select(.CallerReference | \
      startswith(\"$CALLER_REFERENCE_PREFIX\")) | \
      {id: .Id}"
    ;;
esac
