# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "account-alerts" {
  source               = "../../../modules/account-alerts"
  aws_profile          = "${local.aws_profile}"
  env                  = "${local.env}"
  logs_health_check_id = "${local.logs_health_check_id}"
  region               = "${local.region}"
}
