# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "logs_health_check_id" {
  value =  module.account-health-checks.logs_health_check_id
}

output "metrics_health_check_id" {
  value =  module.account-health-checks.metrics_health_check_id
}
